config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'

  # get 'books' => 'books#index'
  # post 'books' => 'books#create'

  # get 'index' => 'books#index'
  # get 'show' => 'books#show'
  # get 'books/:id' => 'books#show'
  # get 'edit' => 'books#edit'
  # get 'top' => 'books#top'
  # delete 'Destroy' => 'destroy'
  resources :books

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end


# GETはデータの取得
# POSTは新しいデータの作成
# PUTは既存データの更新
# PATCHは既存のデータの一部更新
# DELETE	既存のデータを削除

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
      @book = Book.index
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id), notice:'Book was successfully created'
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice:'Book was successfully updated'
    else
      render :edit
    end

  end

  def back
    @book = Book.index
  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to books_path  # 投稿一覧画面へリダイレクト
  end


  private
   # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model: @book do |f| %>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div>
  <label>Title</label>
 <br> <%= f.text_field :title %>
</div>


 <div>
    <label>Body</label>
 <br> <%= f.text_area :body %>
 </div>

 <div>
   <%= f.submit 'Update Book' %>

   <% end %>

  </div>

<span>
 <%= link_to "Show", book_path(@book.id) %>

 |

 <%= link_to "Back", books_path %>
 </span>

app/views/books/index.html.erb
<!--以下全体の表示-->
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
     <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", book_path(book.id) %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td><%= link_to 'Destroy', book_path(book.id), method: :delete, data: {confirm: "Are you sure?"} %></td>
     </tr>
    <% end %>
  </tbody>
</table>


<!--以下新規登録機能について記載-->
<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: '/books', method: :post do |f| %>

  <div>Title</div>
  <%= f.text_field :title %>

 <div>Body</div>
  <%= f.text_area :body %>

  <div>
   <%= f.submit 'Create Book' %>
   </div>
<% end %>

app/views/books/new.html.erb
<!--以下全体の表示-->
<p>Title</p>
<p>Body</p>
<p><colspan="3"></p>


<!--以下新規登録機能について記載-->
<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: '/books', method: :post do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <br/>
  <%= f.submit 'Create Book' %>

<% end %>




 <tbody>
      <tr>
        <td>たのしいRuby</td>
        <td>Rubyの入門におすすめです</td>
        <!--<td><%= link_to "Show", show_book_path(@book.id) %></td>-->
        <!--<td><%= link_to "Edit", edit_book_path(@book.id) %></td>-->
        <td><%= link_to "Destroy", destroy_book_path(@book.id), method: :delete, "data-confirm" => "Are you sure？" %></td>
      </tr>
      <tr>
        <td>入門Git</td>
        <td>gitについての基本操作から内部構造まで解説してくれます</td>
        <!--<td><%= link_to "Show", show_book_path(@book.id) %></td>-->
        <!--<td><%= link_to "Edit", edit_book_path(@book.id) %></td>-->
        <td><%= link_to "Destroy", destroy_book_path(@book.id), method: :delete, "data-confirm" => "Are you sure？" %></td>
      </tr>
      <tr>
        <td>アルゴリズム図鑑</td>
        <td>アルゴリズムについてカラーイラストでしっかり解説してくれます</td>
        <!--<td><%= link_to "Show", show_book_path(@book.id) %></td>-->
        <!--<td><%= link_to "Edit", edit_book_path(@book.id) %></td>-->
        <td><%= link_to "Destroy", destroy_book_path(@book.id), method: :delete, "data-confirm" => "Are you sure？" %></td>
      </tr>
            <tr>
        <td>達人プログラマー</td>
        <td>プログラマ入門者は必読！</td>
        <!--<td><%= link_to "Show", show_book_path(@book.id) %></td>-->
        <!--<td><%= link_to "Edit", edit_book_path(@book.id) %></td>-->
        <td><%= link_to "Destroy", destroy_book_path(@book.id), method: :delete, "data-confirm" => "Are you sure？" %></td>
      </tr>
      <tr>
        <td>データベース実践入門</td>
        <td>効率的なSQL文を教えてくれます</td>
        <!--<td><%= link_to "Show", show_book_path(@book.id) %></td>-->
        <!--<td><%= link_to "Edit", edit_book_path(@book.id) %></td>-->
        <td><%= link_to "Destroy", destroy_book_path(@book.id), method: :delete, "data-confirm" => "Are you sure？" %></td>
      </tr>
      <tr>
        <td>リーダブルコード</td>
        <td>より良いコードを書くためのシンプルで実践なテクニック</td>
        <!--<td><%= link_to "Show", show_book_path(@book.id) %></td>-->
        <!--<td><%= link_to "Edit", edit_book_path(@book.id) %></td>-->
        <td><%= link_to "Destroy", destroy_book_path(@book.id), method: :delete, "data-confirm" => "Are you sure？" %></td>
      </tr>
      <tr>
        <td>楽しいプログラミング</td>
        <td>初心者向け</td>
        <!--<td><%= link_to "Show", show_book_path(@book.id) %></td>-->
        <!--<td><%= link_to "Edit", edit_book_path(@book.id) %></td>-->
        <td><%= link_to "Destroy", destroy_book_path(@book.id), method: :delete, "data-confirm" => "Are you sure？" %></td>
      </tr>
  </tbody>


      <%= link_to "DESTROY", book_path(@book.id), method: :delete, "data-confirm" => "Are you sure？" %>


      <td><%= link_to "Show", show_book_path(book.id) %></td>


<!--indexクリエイト-->
<h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <br/>
  <%= f.submit 'Create Book' %>
  
  
  
  <h4>Book was successfully created.</h4>
  
  
  <!--.notifications-->
  <!--   - flash.each do |key, value|-->
  <!--    = content_tag(:div, value, class: key)-->


book = Book.find(params[:id])
    book.update(book_params)
    redirect_to book_path(book.id), notice:'Book was successfully updated'
    

app/views/books/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @book.title %>
</p>

<p>
    <strong>Body:</strong>
    <%= @book.body %>
</p>

<span>
 <%= link_to "Edit", edit_book_path(@book.id) %>

 |

 <%= link_to "Back", books_path %>
</span>

app/views/homes/top.html.erb
<h1>
  ようこそ
  <strong>Bookers</strong>
  へ！
</h1>

<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や
</p>
<p>印象を共有し交換することができます</p>

<p>
  <a href="/books">start</a>
</p>

<!--<p>Find me in app/views/homes/top.html.erb</p>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">

  </head>

  <body>
    <%= notice %>

     <%= yield %>
  </body>
</html>